version: '3.4'

services:

  mongo:
    image: mongo:4.4
    container_name: mongodb
    hostname: mongodb
    restart: unless-stopped
    environment:
      MONGO_REPLICA_SET_NAME: rs0
    volumes:
      - $PWD/DBdata:/data/db
      - $PWD/mongod.conf:/etc/mongod.conf
      - $PWD/mongodb-keyfile:/data/mongodb-keyfile
    networks:
      macnet:
        ipv4_address: 192.168.50.17
    healthcheck:
      test: test $$(echo "rs.initiate().ok || rs.status().ok" | mongo -u $${MONGO_INITDB_ROOT_USERNAME} -p $${MONGO_INITDB_ROOT_PASSWORD} --quiet) -eq 1
      interval: 60s
      timeout: 30s
      retries: 5
      start_period: 30s
    command: "mongod --bind_ip_all --replSet rs0 --keyFile /data/mongodb-keyfile"

networks:
  macnet:
    external: true
